### ISSUE TITLE
Add mocks and stuff for saving things to the database

### ISSUE THREAD

**Issue by brittany2e** [brittany2e/dotnetcore-fsharp-api#6]
Move weather stuff to Repositories and Domain files (instead of the client). We use Postgres with our other Fsharp api.

**Comment by matthewcrews** [comment]
Which library do you use for interacting with the DB?

**Comment by brittany2e** [comment]
We use this thin wrapper around Postgres https://github.com/Zaid-Ajaj/Npgsql.FSharp
It has worked pretty well and was easy to pick up.

Using the wrapper looks like this
```
open Npgsql.FSharp.OptionWorkflow
open Microsoft.Extensions.Options

module WeatherForecast=
    type WeatherForecastRepository(options: IOptions<StorageSettings>) =

        let settings = options.Value

        let getWeather (date:DateTime) =
            settings.ConnectionString
            |> Sql.connect
            |> Sql.query "select * from weather where date = @date"
            |> Sql.parameters ["date", Sql.Value date]
            |> Sql.executeTable
            |> Sql.parseEachRow<WeatherDto>
            |> List.head

        member _.GetWeather date =
            getWeather date

```

I first tried something else, but I had errors with TypeProviders.

**Comment by brittany2e** [comment]
Done in https://github.com/brittany2e/dotnetcore-fsharp-api/pull/8
